// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBApoXKajRdYMqVrw89t5EwpoEP2ZoyP-U',
    appId: '1:1054106737927:web:a333c6a6a10d1c8418b9a2',
    messagingSenderId: '1054106737927',
    projectId: 'smartindiahackathon-25234',
    authDomain: 'smartindiahackathon-25234.firebaseapp.com',
    storageBucket: 'smartindiahackathon-25234.appspot.com',
    measurementId: 'G-93G1GBJ4Z8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0Zhqa7WZP7aKQAveHudk9Oz6eWNiTr_U',
    appId: '1:1054106737927:android:1ccd861c2adb7f0718b9a2',
    messagingSenderId: '1054106737927',
    projectId: 'smartindiahackathon-25234',
    storageBucket: 'smartindiahackathon-25234.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOuCOF88xbk0PduulHR1jc4qvZOThKFHU',
    appId: '1:1054106737927:ios:50c634cad3c3a13018b9a2',
    messagingSenderId: '1054106737927',
    projectId: 'smartindiahackathon-25234',
    storageBucket: 'smartindiahackathon-25234.appspot.com',
    iosBundleId: 'com.example.sihSos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOuCOF88xbk0PduulHR1jc4qvZOThKFHU',
    appId: '1:1054106737927:ios:d14d95119953b46a18b9a2',
    messagingSenderId: '1054106737927',
    projectId: 'smartindiahackathon-25234',
    storageBucket: 'smartindiahackathon-25234.appspot.com',
    iosBundleId: 'com.example.sihSos.RunnerTests',
  );
}
